Repository PKP-Park-Kim-Park/Project-Slotmachine, pull requests merged in 2025-09, with the labels that each got.

#44 34 슬롯 머신 화면 UI
  Assets/ExterialAssets/Image.meta
  Assets/ExterialAssets/Image/bell.png
  Assets/ExterialAssets/Image/bell.png.meta
  Assets/ExterialAssets/Image/cherry.png
  Assets/ExterialAssets/Image/cherry.png.meta
  Assets/ExterialAssets/Image/diamond.png
  Assets/ExterialAssets/Image/diamond.png.meta
  Assets/ExterialAssets/Image/lemon.png
  Assets/ExterialAssets/Image/lemon.png.meta
  Assets/ExterialAssets/Image/orange.png
  Assets/ExterialAssets/Image/orange.png.meta
  Assets/ExterialAssets/Image/seven.png
  Assets/ExterialAssets/Image/seven.png.meta
  Assets/ExterialAssets/Image/star.png
  Assets/ExterialAssets/Image/star.png.meta
  Assets/Prefabs/Doorway.prefab
  Assets/Prefabs/GameManager.prefab
  Assets/Prefabs/ReelViewport.prefab
  Assets/Prefabs/ReelViewport.prefab.meta
  Assets/Prefabs/Slotmachine.prefab
  Assets/Scenes/PSH.unity
  Assets/Scripts/Reel/Reel.cs
  Assets/Scripts/Reel/ReelAnimator.cs
  Assets/Scripts/Reel/ReelAnimator.cs.meta
  Assets/Scripts/Reel/ReelTest.cs
  Assets/Scripts/Reel/SymbolManager.cs
  Assets/Scripts/Reel/SymbolManager.cs.meta
  Assets/Scripts/Slotmachine/LeverMotion.cs
  Assets/Scripts/Slotmachine/SlotMachine.cs
  Assets/Scripts/Symbols.cs
Labels: enhancement

#52 스탑벨 오브젝트 제작 및, 프리팹 추가
  Assets/ExterialAssets/QuickOutline/Scripts/Outline.cs
  Assets/Prefabs/StopBell.prefab
  Assets/Prefabs/StopBell.prefab.meta
  Assets/Scenes/MainScene.unity
Labels: enhancement

#54 패턴 로직 구현
  Assets/Scripts/Slotmachine/CheckRewardParttern.cs
  Assets/Scripts/Slotmachine/CheckRewardParttern.cs.meta
Labels: enhancement

#56 40 타이틀 UI 임시 작성
  Assets/Prefabs/Map.prefab
  Assets/Scenes/MainScene.unity
  Assets/Scenes/PSH.unity
  Assets/Scenes/Title.unity
  Assets/Scenes/Title.unity.meta
  Assets/Scripts/TitleManager.cs
  Assets/Scripts/TitleManager.cs.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#55 퍼즈 UI & 마우스 감도 & AudioMIxer 구현
  Assets/Audio.meta
  Assets/Audio/BGM.mixer
  Assets/Audio/BGM.mixer.meta
  Assets/Audio/SFX.mixer
  Assets/Audio/SFX.mixer.meta
  Assets/Scenes/KTW.unity
  Assets/Scripts/GameManager.cs
  Assets/Scripts/Player/PlayerLook.cs
  Assets/Scripts/SettingManager.cs
  Assets/Scripts/SettingManager.cs.meta
Labels: enhancement

#71 디버그 로그 수정/제거
  Assets/Scenes/PSH.unity
  Assets/Scripts/Door/AutoLockTrigger.cs
  Assets/Scripts/Door/Door.cs
  Assets/Scripts/Door/Unlock.cs
  Assets/Scripts/Interface/IInteractable.cs
  Assets/Scripts/Money/StopBell.cs
  Assets/Scripts/Player/PlayerController.cs
  Assets/Scripts/Player/PlayerLook.cs
  Assets/Scripts/Player/Sphere.cs
  Assets/Scripts/Player/Sphere.cs.meta
  Assets/Scripts/Player/ViewFix.cs
  Assets/Scripts/Reel/PatternAnimator.cs
  Assets/Scripts/Reel/SymbolManager.cs
  Assets/Scripts/Slotmachine/LeverMotion.cs
  Assets/Scripts/Slotmachine/SlotMachine.cs
Labels: Cleaner

#75 68 잡다구리 수정
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/Slotmachine.prefab
  Assets/Scripts/GameManager.cs
  Assets/Scripts/Money/Money.cs
  Assets/Scripts/Money/StopBell.cs
  Assets/Scripts/Player/PlayerController.cs
  Assets/Scripts/Slotmachine/BtnMotion.cs
  Assets/Scripts/UIManager.cs
Labels: enhancement

#74 맵2 디자인
  Assets/ExterialAssets/Map/Pandazole_Lowpoly_Asset_Bundle/Pandazole Nature Environment Pack/Materials/PandaMat.mat
  Assets/ExterialAssets/Map/Pandazole_Lowpoly_Asset_Bundle/Pandazole Survival Crafting Pack/Materials/PandaMat.mat
  Assets/ExterialAssets/New Render Texture.renderTexture
  Assets/ExterialAssets/New Render Texture.renderTexture.meta
  Assets/ExterialAssets/pkp.png
  Assets/ExterialAssets/pkp.png.meta
  Assets/ExterialAssets/영상.mp4
  Assets/ExterialAssets/영상.mp4.meta
  Assets/Prefabs/Map.prefab
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/SettingUI.prefab
  Assets/Prefabs/SettingUI.prefab.meta
  Assets/Scenes/KTW.unity
  Assets/Scenes/MainScene.unity
Labels: enhancement

#83 세이브 & 로드 기능 구현
  Assets/Prefabs/DataManager.prefab
  Assets/Prefabs/DataManager.prefab.meta
  Assets/Prefabs/Player.prefab
  Assets/Scenes/MainScene.unity
  Assets/Scenes/Title.unity
  Assets/Scripts/GameManager.cs
  Assets/Scripts/Player/PlayerController.cs
  Assets/Scripts/Save.meta
  Assets/Scripts/Save/DataManager.cs
  Assets/Scripts/Save/DataManager.cs.meta
  Assets/Scripts/Save/GameData.cs
  Assets/Scripts/Save/GameData.cs.meta
  Assets/Scripts/TitleManager.cs
Labels: enhancement

#87 85 슬롯머신 위쪽에 당첨 결과 띄우기 화면에 총합배율 띄우기
  Assets/Materials/Minus.mat
  Assets/Materials/Plus.mat
  Assets/Prefabs/Slotmachine.prefab
  Assets/Scenes/PSH.unity
  Assets/Scripts/Slotmachine/BetScreen.cs
  Assets/Scripts/Slotmachine/BetScreen.cs.meta
  Assets/Scripts/Slotmachine/LeverMotion.cs
  Assets/Scripts/Slotmachine/RewardScreen.cs
  Assets/Scripts/Slotmachine/RewardScreen.cs.meta
  Assets/Scripts/Slotmachine/SlotMachine.cs
Labels: enhancement

#98 저장 나가기 버튼 연동 및 씬 전환될때 오류 수정
  Assets/Prefabs/SettingUI.prefab
  Assets/Scripts/Player/PlayerController.cs
  Assets/Scripts/SettingManager.cs
Labels: enhancement

#102 이벤트 시스템을 이용한 설정 메뉴 활성화 조건 추가
  Assets/Scripts/GameManager.cs
  Assets/Scripts/Player/PlayerLook.cs
  Assets/Scripts/SettingManager.cs
Labels: enhancement

#119 시점 고정 전환 방법
  Assets/Scripts/Player/PlayerLook.cs
Labels: bug

#122 114 아이템의 데이터 추가
  Assets/ScriptableObject/ItemData.cs
  Assets/ScriptableObject/ItemData.cs.meta
  Assets/ScriptableObject/ItmeData.asset
  Assets/ScriptableObject/ItmeData.asset.meta
Labels: enhancement

#123 프리팹이랑 플레이어 룩 변수명 수정
  Assets/Prefabs/SettingUI.prefab
  Assets/Scripts/Player/PlayerLook.cs
Labels: enhancement

#124 113 player에게 스트레스값 추가
  Assets/Prefabs/Player.prefab
  Assets/Scenes/KTW.unity
  Assets/Scripts/Player/PlayerStress.cs
  Assets/Scripts/Player/PlayerStress.cs.meta
  Assets/Scripts/UIManager.cs
Labels: enhancement

#126 112 useitem 클래스 만들기
  Assets/ScriptableObject/ItemData.asset
  Assets/ScriptableObject/ItemData.asset.meta
  Assets/ScriptableObject/ItemData.cs
  Assets/Scripts/Item.meta
  Assets/Scripts/Item/UseItem.cs
  Assets/Scripts/Item/UseItem.cs.meta
Labels: enhancement

#127 111 levelmanager 클래스 만들기
  Assets/Prefabs/Doorway.prefab
  Assets/Prefabs/GameManager.prefab
  Assets/Prefabs/Key.prefab
  Assets/Prefabs/Key.prefab.meta
  Assets/Scenes/MainScene.unity
  Assets/Scenes/PSH.unity
  Assets/ScriptableObject/SymbolWeight.asset
  Assets/Scripts/Door/AutoLockTrigger.cs
  Assets/Scripts/Door/Door.cs
  Assets/Scripts/Door/KeySpawner.cs
  Assets/Scripts/Door/KeySpawner.cs.meta
  Assets/Scripts/Door/Unlock.cs
  Assets/Scripts/Enum/Symbols.cs
  Assets/Scripts/GameManager.cs
  Assets/Scripts/Level/LevelData.cs
  Assets/Scripts/LevelManager.cs
  Assets/Scripts/LevelManager.cs.meta
  Assets/Scripts/Slotmachine/BetScreen.cs
  Assets/Scripts/Slotmachine/BtnMotion.cs
  Assets/Scripts/Slotmachine/LeverMotion.cs
  Assets/Scripts/Slotmachine/SlotMachine.cs
Labels: enhancement

#132 아이템 추가
  Assets/ScriptableObject/ItemData.asset
Labels: enhancement

#134 130 아이템 인벤토리 샵 useitem 유기적으로 연결
  Assets/ScriptableObject/ItemData.cs
  Assets/Scripts/GameManager.cs
  Assets/Scripts/Item/ItemManager.cs
  Assets/Scripts/Item/Shop.cs
  Assets/Scripts/Item/TestRunner.cs
  Assets/Scripts/Item/UseItem.cs
  Assets/Scripts/Player/Inventory.cs
Labels: enhancement

#137 135 나머지 심볼 스프라이트 및 애니매이션
  Assets/ExterialAssets/Image/Border 1.png
  Assets/ExterialAssets/Image/Border 1.png.meta
  Assets/ExterialAssets/Image/Border.png
  Assets/ExterialAssets/Image/Border.png.meta
  Assets/ExterialAssets/Image/Symbols/Carrot-Sheet.png
  Assets/ExterialAssets/Image/Symbols/Carrot-Sheet.png.meta
  Assets/ExterialAssets/Image/Symbols/Carrot.png
  Assets/ExterialAssets/Image/Symbols/cherry-Sheet.png
  Assets/ExterialAssets/Image/Symbols/cherry-Sheet.png.meta
  Assets/ExterialAssets/Image/Symbols/cherry.png
  Assets/ExterialAssets/Image/Symbols/skull-Sheet.png
  Assets/ExterialAssets/Image/Symbols/skull-Sheet.png.meta
  Assets/Prefabs/BorderImage.prefab
  Assets/Prefabs/GameManager.prefab
  Assets/Prefabs/ReelViewport.prefab
  Assets/Prefabs/Slotmachine.prefab
  Assets/Scenes/PSH.unity
Labels: enhancement

#136 103 심볼 확률배당 보여주는 UI 작업
  Assets/Prefabs/Plane.prefab
  Assets/Prefabs/Plane.prefab.meta
  Assets/Prefabs/Symbol_Chart.prefab
  Assets/Prefabs/Symbol_Chart.prefab.meta
  Assets/Scenes/MainScene.unity
  Assets/Scenes/Shop.unity
  Assets/ScriptableObject/RarityProbabilityTable.asset
  Assets/ScriptableObject/SymbolRewardOdds.cs
  Assets/Scripts/Display.meta
  Assets/Scripts/Display/SymbolUIManager.cs
  Assets/Scripts/Display/SymbolUIManager.cs.meta
Labels: enhancement

#140 139 심볼 차트 텍스트 연동 수정
  Assets/Prefabs/GameManager.prefab
  Assets/Prefabs/ItemManager.prefab
  Assets/Prefabs/ItemManager.prefab.meta
  Assets/Prefabs/Map.prefab
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/Symbol_Chart.prefab
  Assets/Scenes/MainScene.unity
  Assets/Scenes/Title.unity
  Assets/ScriptableObject/ItemData.asset
  Assets/ScriptableObject/SymbolRewardOdds.asset
  Assets/Scripts/GameManager.cs
Labels: enhancement
